[package]
name = "chess-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
enum_dispatch = "0.3.8"
lazy_static = "1.4.0"
macroquad = "0.3.25"
maplit = "1.0.2"
